import { KeywordGapData } from "@/app/components/keyword-gap/api";

export const mockKeywordGapData: KeywordGapData = {
  seller_keywords: [
    "women",
    "cotton",
    "western",
    "midi",
    "dress",
    "summer",
    "casual",
    "puff",
    "sleeves",
    "round",
    "neck",
    "printed",
    "flared",
    "wrap",
    "fabric",
    "dresses",
    "pure",
    "lightweight",
    "soft",
    "comfortable",
    "wear",
    "spring",
    "fall",
    "features",
    "stretchy",
    "bodice",
    "ruffle",
    "cuffs",
    "belly",
    "feminine",
    "beach",
    "vacation",
    "daily",
    "baby shower",
    "maternity",
    "dating",
    "holiday",
    "wedding guest",
    "travel",
    "sandals",
    "high heeled",
  ],

  competitor_keywords: [
    "dress",
    "women",
    "length",
    "midi",
    "material",
    "style",
    "occasion",
    "highlights",
    "material type",
    "type",
    "sleeve",
    "neck",
    "casual",
    "about",
    "occasion type",
    "item",
    "dress for",
    "midi dress",
    "summer",
    "origin",
    "country",
    "india",
    "women s",
    "wear",
    "for women",
    "stylish",
    "sleeves",
    "piece",
    "line",
    "cotton",
    "fabric",
    "cotton length",
    "one",
    "one piece",
    "floral",
    "sleeve type",
    "western",
    "lightweight",
    "comfort",
    "printed",
    "puff",
    "v neck",
    "type cotton",
    "a line",
    "casual summer",
    "sleeve style",
    "crafted",
    "knee length",
    "ankle length",
    "fit and flare",
    "anarkali",
    "tiered",
    "smock",
    "pleated",
    "flutter sleeves",
    "georgette",
    "rayon",
    "polyester",
    "party",
    "birthday",
    "diwali",
    "office",
    "date",
    "evening",
    "gown",
    "frock",
    "calf length",
  ],

  missing_critical: [
    {
      keyword: "one piece",
      competitor_coverage: 5,
      gap_type: "both",
      suggested_placement: "title",
      intent_type: "discovery",
    },
    {
      keyword: "a line",
      competitor_coverage: 4,
      gap_type: "both",
      suggested_placement: "bullet_2",
      intent_type: "discovery",
    },
    {
      keyword: "v neck",
      competitor_coverage: 4,
      gap_type: "both",
      suggested_placement: "title",
      intent_type: "discovery",
    },
    {
      keyword: "stylish",
      competitor_coverage: 6,
      gap_type: "both",
      suggested_placement: "bullet_2",
      intent_type: "discovery",
    },
    {
      keyword: "floral",
      competitor_coverage: 5,
      gap_type: "both",
      suggested_placement: "title",
      intent_type: "discovery",
    },
    {
      keyword: "for women",
      competitor_coverage: 8,
      gap_type: "frontend",
      suggested_placement: "title",
      intent_type: "discovery",
    },
    {
      keyword: "fit and flare",
      competitor_coverage: 3,
      gap_type: "both",
      suggested_placement: "bullet_2",
      intent_type: "discovery",
    },
    {
      keyword: "knee length",
      competitor_coverage: 2,
      gap_type: "both",
      suggested_placement: "bullet_3",
      intent_type: "discovery",
    },
  ],

  missing_secondary: [
    {
      keyword: "anarkali",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "frock",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "gown",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "tiered dress",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "smock dress",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "use_case",
    },
    {
      keyword: "pleated dress",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "office wear",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "use_case",
    },
    {
      keyword: "party dress",
      competitor_coverage: 2,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "use_case",
    },
    {
      keyword: "diwali",
      competitor_coverage: 2,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "use_case",
    },
    {
      keyword: "birthday dress",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "use_case",
    },
    {
      keyword: "calf length",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
    {
      keyword: "flutter sleeves",
      competitor_coverage: 1,
      gap_type: "backend",
      suggested_placement: "backend",
      intent_type: "discovery",
    },
  ],

  content_gaps: [
    "No 'one piece' phrasing anywhere in title or bullets — 5 of 10 competitors use it. Buyers searching 'one piece dress for women' won't find this listing.",
    "V-neck is absent from the listing despite 4 competitors flagging it. The description contradicts itself by calling the neck 'round' then describing a V-shaped cutout. Resolve this: if it's a wrap-style V-neckline, call it out explicitly in the title.",
    "'A-line' or 'fit and flare' silhouette terms are missing from bullets and title. 4 competitors use these — they're the primary shape descriptors buyers filter by on Amazon IN.",
    "No occasion keywords like 'party', 'office', or 'birthday' in the listing beyond the generic occasions bullet. Competitors with higher conversion visibility cover these in titles and bullets.",
    "Country of origin ('India') is absent from visible listing content. 7 of 10 competitors surface it — it's a trust signal and indexed attribute on Amazon IN.",
    "'Stylish' appears in 6 competitor titles but zero seller content — low byte cost, high coverage gap. Add to a bullet or title where organic.",
    "Floral print is mentioned by 5 competitors but the seller uses only 'printed' — the specific print type helps buyers searching 'floral print dress' find the listing.",
  ],

  rewritten_title_snippet:
    "Women Cotton One Piece Floral Printed Midi Dress | A-Line Fit & Flare V-Neck Puff Sleeves Casual Summer Wrap Dress for Women",

  backend_audit: {
    current_bytes_used: 0,
    bytes_available: 249,
    current_duplicates: [],
    current_internal_dupes: [],
    compliance_issues: [],
  },

  generated_backend_string:
    "anarkali frock gown kurti style tiered smock pleated a line fit flare knee length calf length party office birthday diwali date evening sundress maxi flutter half sleeve breathable india made ड्रेस",

  backend_keyword_sets: {
    synonyms: ["anarkali", "frock", "gown", "kurti style", "sundress", "maxi"],
    long_tail: [
      "tiered smock pleated a line",
      "fit flare knee length",
      "calf length flutter half sleeve",
    ],
    spelling_variants: [],
    numeric_text_pairs: [],
    intent_phrases: ["party office birthday diwali date evening"],
    locale_variants: ["ड्रेस"],
    seasonal: ["diwali", "rakhi gift for sister", "monsoon dress"],
    ppc_harvest: [],
  },

  backend_byte_plan: {
    total_available: 249,
    allocated: 207,
    remaining: 42,
    slot_breakdown: [
      {
        keyword_group: "synonyms + long_tail",
        bytes_used: 112,
        priority: 1,
      },
      {
        keyword_group: "intent_phrases + locale_variants",
        bytes_used: 72,
        priority: 2,
      },
      {
        keyword_group: "numeric_text_pairs + spelling_variants",
        bytes_used: 27,
        priority: 3,
      },
      {
        keyword_group: "ppc_harvest (reserved)",
        bytes_used: 19,
        priority: 4,
      },
    ],
  },

  indexation_gap_score: 25,
};